### ISSUE TITLE
Plugin can't sign into UserDeck account

### ISSUE THREAD

**Issue by Clarimmy** [userdeck/wordpress-plugin#3] opened 2018-03-12 20:52 UTC
The settings page doesn't work after you click "Sign In". It comes comes up with a blank iframe
https://i.imgur.com/50QZSV4.png

If you look in the console, you get the following error message:
------------
Refused to display 'https://app.userdeck.com/install' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

**Comment by dmyers** [comment] 2018-03-13 20:25
Thank you for reporting this. It was just recently reported to us and we've been looking to see the cause whether or not it was a browser change or one that was from our end and it turned out the root cause was in our web server when we switched hosing providers and we're unsure if it was automated change or since the switch since it was just recently discovered, but it is now fixed.

**Closed as completed by dmyers** 2018-03-13 20:25 UTC
